{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with $.Values.elementCall -}}
{{- if .enabled -}}
{{- with .sfu -}}
{{- if .enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.element-call-sfu.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-element-call-sfu
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |
    {{- tpl ($.Files.Get "configs/element-call/sfu/config.yaml.tpl") (dict "root" $ "context" .) | nindent 4 }}
  keys.yaml: |
    ${LIVEKIT_KEY}: ${LIVEKIT_SECRET}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
