{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with .Values.elementCall.sfu -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.element-call.sfu.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-element-call-sfu
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |
    {{- tpl ($.Files.Get "configs/element-call/sfu/config.yaml.tpl") (dict "root" $ "context" .) | nindent 4 }}
  keys.yaml: |
    {{ printf "{{ readfile \"/secrets/%s\" | quote }}" (
          include "element-io.ess-library.init-secret-path" (
              dict "root" $root
              "context" (dict
                "secretPath" "elementCall.livekitKey"
                "initSecretKey" "ELEMENT_CALL_LIVEKIT_KEY"
                "defaultSecretName" (printf "%s-element-call" $root.Release.Name)
                "defaultSecretKey" "LIVEKIT_KEY"
              )
          )
        ) }}: {{ printf "{{ readfile \"/secrets/%s\" | quote }}" (
          include "element-io.ess-library.init-secret-path" (
              dict "root" $root
              "context" (dict
                "secretPath" "elementCall.livekitSecret"
                "initSecretKey" "ELEMENT_CALL_LIVEKIT_SECRET"
                "defaultSecretName" (printf "%s-element-call" $root.Release.Name)
                "defaultSecretKey" "LIVEKIT_SECRET"
              )
          )
        ) }}
{{- end -}}
