# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

elementCall:
  ingress:
    host: call.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-element-call-tls"
  extraEnv:
  - name: LIVEKIT_INSECURE_SKIP_VERIFY_TLS
    value: "YES_I_KNOW_WHAT_I_AM_DOING"
  sfu:
    extraEnv:
    - name: DEBUG_RENDERING
      value: "1"
    podSecurityContext:
      runAsGroup: 0
  podSecurityContext:
    runAsGroup: 0
