# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

serverName: ess.localhost

elementWeb:
  ingress:
    host: element.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-element-web-tls"

  replicas: 1

  annotations:
    has-no-service-monitor: "true"

  podSecurityContext:
    runAsGroup: 0

  additional:
    user-config.json: |
      {
        "default_server_config": {
          "m.homeserver": {
            "base_url": "https://synapse.{{ $.Values.serverName }}"
          }
        },
        "element_call": {
          "url": "https://mrtc.{{ $.Values.serverName }}",
          "use_exclusively": true
        },
        "features": {
          "feature_video_rooms": true,
          "feature_group_calls": true,
          "feature_new_room_decoration_ui": true,
          "feature_element_call_video_rooms": true
        }
      }
